services:
  - type: web
    name: televizion-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.mjs
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        value: d433b9c6e1e1ae541c2707d670dd7a7e
