/**
 * Обширная база популярных фильмов, сериалов, мультфильмов и аниме
 * для богатого каталога HDRezka на Smart TV.
 */

export const REZKA_DEMO_QUALITIES = []

export const REZKA_MOVIES_DB = [
  // ==================== ФИЛЬМЫ ====================
  {
    id: '71420',
    kinopoiskId: '4447385',
    imdbId: 'tt15239678',
    title: 'Дюна: Часть вторая',
    origTitle: 'Dune: Part Two',
    categories: ['films', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '8.5',
    ratingImdb: '8.6',
    genres: 'Фантастика, Боевик, Приключения',
    country: 'США',
    duration: '166 мин.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    description: 'Герцог Пол Атрейдес объединяется с Чани и фременами, чтобы отомстить заговорщикам, уничтожившим его семью.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж (Red Head Sound)', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
      { id: '1', name: 'Оригинал (Eng)' },
    ],
  },
  {
    id: '68214',
    kinopoiskId: '4664634',
    imdbId: 'tt15398776',
    title: 'Оппенгеймер',
    origTitle: 'Oppenheimer',
    categories: ['films', 'new'],
    quality: '1080p Ultra',
    year: '2023',
    ratingKp: '8.2',
    ratingImdb: '8.9',
    genres: 'Биография, Драма, История',
    country: 'США, Великобритания',
    duration: '180 мин.',
    poster: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&auto=format&fit=crop&q=80',
    description: 'История жизни американского физика-теоретика Роберта Оппенгеймера, руководителя Манхэттенского проекта.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж (LineTree)', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
  },
  {
    id: '49112',
    kinopoiskId: '258687',
    imdbId: 'tt0816692',
    title: 'Интерстеллар',
    origTitle: 'Interstellar',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2014',
    ratingKp: '8.6',
    ratingImdb: '8.7',
    genres: 'Фантастика, Драма, Приключения',
    country: 'США, Великобритания',
    duration: '169 мин.',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    description: 'Коллектив исследователей отправляется сквозь червоточину в поисках нового дома для гибнущего человечества.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж', isDefault: true },
      { id: '1', name: 'Оригинал (Eng)' },
    ],
  },
  {
    id: '58410',
    kinopoiskId: '1309570',
    imdbId: 'tt10872600',
    title: 'Человек-паук: Нет пути домой',
    origTitle: 'Spider-Man: No Way Home',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2021',
    ratingKp: '8.0',
    ratingImdb: '8.2',
    genres: 'Фантастика, Боевик, Приключения',
    country: 'США',
    duration: '148 мин.',
    poster: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=600&auto=format&fit=crop&q=80',
    description: 'Жизнь Питера Паркера переворачивается, когда его личность разоблачают. Он обращается за помощью к Доктору Стрэнджу.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
  },
  {
    id: '12401',
    kinopoiskId: '838',
    imdbId: 'tt0145487',
    title: 'Человек-паук',
    origTitle: 'Spider-Man',
    categories: ['films'],
    quality: '1080p',
    year: '2002',
    ratingKp: '7.7',
    ratingImdb: '7.4',
    genres: 'Фантастика, Боевик, Приключения',
    country: 'США',
    duration: '121 мин.',
    poster: 'https://images.unsplash.com/photo-1604200213928-ba3cf4fc8436?w=600&auto=format&fit=crop&q=80',
    description: 'Скромный студент Питер Паркер получает невероятные суперспособности после укуса генетически модифицированного паука.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
  },
  {
    id: '25419',
    kinopoiskId: '462449',
    imdbId: 'tt0258280',
    title: 'Новый Человек-паук',
    origTitle: 'The Amazing Spider-Man',
    categories: ['films'],
    quality: '1080p',
    year: '2012',
    ratingKp: '6.9',
    ratingImdb: '6.9',
    genres: 'Фантастика, Боевик, Приключения',
    country: 'США',
    duration: '136 мин.',
    poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    description: 'Питер Паркер пытается разгадать тайну исчезновения своих родителей и сталкивается со смертоносным Ящером.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '67412',
    kinopoiskId: '1318891',
    imdbId: 'tt6263850',
    title: 'Дэдпул и Росомаха',
    origTitle: 'Deadpool & Wolverine',
    categories: ['films', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '7.7',
    ratingImdb: '7.8',
    genres: 'Боевик, Комедия, Фантастика',
    country: 'США',
    duration: '128 мин.',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    description: 'Уэйд Уилсон объединяется с нелюдимым Росомахой ради спасения своей родной вселенной от гибели.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж (Red Head Sound)', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
  },
  {
    id: '51204',
    kinopoiskId: '505898',
    imdbId: 'tt1630029',
    title: 'Аватар: Путь воды',
    origTitle: 'Avatar: The Way of Water',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2022',
    ratingKp: '7.8',
    ratingImdb: '7.6',
    genres: 'Фантастика, Боевик, Приключения',
    country: 'США',
    duration: '192 мин.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    description: "Джейк Салли и Нейтири защищают свою семью и народ на'ви, исследуя океанские глубины Пандоры.",
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '34190',
    kinopoiskId: '1143242',
    imdbId: 'tt8962124',
    title: 'Джентльмены',
    origTitle: 'The Gentlemen',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2020',
    ratingKp: '8.6',
    ratingImdb: '7.8',
    genres: 'Криминал, Комедия, Боевик',
    country: 'Великобритания, США',
    duration: '113 мин.',
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    description: 'Талантливый выпускник Оксфорда придумал дерзкую схему обогащения. Но когда он решает продать бизнес, начинается война.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж (Гоблин)', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
  },
  {
    id: '48120',
    kinopoiskId: '841081',
    imdbId: 'tt1877830',
    title: 'Бэтмен',
    origTitle: 'The Batman',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2022',
    ratingKp: '7.9',
    ratingImdb: '7.8',
    genres: 'Детектив, Криминал, Драма, Боевик',
    country: 'США',
    duration: '176 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Брюс Уэйн расследует серию жестоких убийств элиты Готэма, организованных Загадочником.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж (Red Head Sound)', isDefault: true }],
  },
  {
    id: '32001',
    kinopoiskId: '447301',
    imdbId: 'tt1375666',
    title: 'Начало',
    origTitle: 'Inception',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2010',
    ratingKp: '8.7',
    ratingImdb: '8.8',
    genres: 'Фантастика, Боевик, Триллер',
    country: 'США, Великобритания',
    duration: '148 мин.',
    poster: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=600&auto=format&fit=crop&q=80',
    description: 'Кобб — непревзойденный вор секретов из глубин подсознания во время сна. Ему предстоит совершить обратное: внедрить идею.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '29871',
    kinopoiskId: '111543',
    imdbId: 'tt0468569',
    title: 'Темный рыцарь',
    origTitle: 'The Dark Knight',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2008',
    ratingKp: '8.5',
    ratingImdb: '9.0',
    genres: 'Боевик, Криминал, Драма',
    country: 'США, Великобритания',
    duration: '152 мин.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    description: 'Бэтмен поднимает ставки в войне с криминалом, но сталкивается с гением хаоса по прозвищу Джокер.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '15401',
    kinopoiskId: '301',
    imdbId: 'tt0133093',
    title: 'Матрица',
    origTitle: 'The Matrix',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '1999',
    ratingKp: '8.5',
    ratingImdb: '8.7',
    genres: 'Фантастика, Боевик',
    country: 'США, Австралия',
    duration: '136 мин.',
    poster: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    description: 'Хакер Нео узнает ужасную правду: мир вокруг — иллюзия, созданная машинами для порабощения человечества.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '61450',
    kinopoiskId: '1267348',
    imdbId: 'tt10366206',
    title: 'Джон Уик 4',
    origTitle: 'John Wick: Chapter 4',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2023',
    ratingKp: '7.6',
    ratingImdb: '7.7',
    genres: 'Боевик, Триллер, Криминал',
    country: 'США, Германия',
    duration: '169 мин.',
    poster: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=600&auto=format&fit=crop&q=80',
    description: 'Джон Уик находит способ победить Правление Кланов, но перед этим ему предстоит одолеть армию старых и новых врагов.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '73411',
    kinopoiskId: '4780526',
    imdbId: 'tt9218128',
    title: 'Гладиатор 2',
    origTitle: 'Gladiator II',
    categories: ['films', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '7.3',
    ratingImdb: '7.1',
    genres: 'Боевик, Драма, Приключения, История',
    country: 'Великобритания, США',
    duration: '148 мин.',
    poster: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=600&auto=format&fit=crop&q=80',
    description: 'Спустя годы после гибели Максимуса Луций вступает на арену Колизея, чтобы вернуть Риму былую славу.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж (Red Head Sound)', isDefault: true }],
  },
  {
    id: '11200',
    kinopoiskId: '301',
    imdbId: 'tt0133093',
    title: 'Бойцовский клуб',
    origTitle: 'Fight Club',
    categories: ['films'],
    quality: '1080p',
    year: '1999',
    ratingKp: '8.7',
    ratingImdb: '8.8',
    genres: 'Триллер, Драма, Криминал',
    country: 'США, Германия',
    duration: '139 мин.',
    poster: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&auto=format&fit=crop&q=80',
    description: 'Страдающий бессонницей клерк знакомится с торговцем мылом Тайлером Дёрденом, исповедующим философию саморазрушения.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '10502',
    kinopoiskId: '435',
    imdbId: 'tt0120689',
    title: 'Зеленая миля',
    origTitle: 'The Green Mile',
    categories: ['films'],
    quality: '1080p',
    year: '1999',
    ratingKp: '9.1',
    ratingImdb: '8.6',
    genres: 'Драма, Фэнтези, Криминал',
    country: 'США',
    duration: '189 мин.',
    poster: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&auto=format&fit=crop&q=80',
    description: 'Пол Эджкомб работает в блоке смертников, куда прибывает Джон Коффи — гигант, наделенный целительным даром.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '10401',
    kinopoiskId: '326',
    imdbId: 'tt0111161',
    title: 'Побег из Шоушенка',
    origTitle: 'The Shawshank Redemption',
    categories: ['films'],
    quality: '1080p',
    year: '1994',
    ratingKp: '9.1',
    ratingImdb: '9.3',
    genres: 'Драма',
    country: 'США',
    duration: '142 мин.',
    poster: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=600&auto=format&fit=crop&q=80',
    description: 'Бухгалтер Энди Дюфрейн осужден за преступление, которого не совершал, и оказывается в мрачной тюрьме Шоушенк.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '28400',
    kinopoiskId: '447301',
    imdbId: 'tt1375666',
    title: 'Волк с Уолл-стрит',
    origTitle: 'The Wolf of Wall Street',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2013',
    ratingKp: '8.0',
    ratingImdb: '8.2',
    genres: 'Биография, Комедия, Криминал',
    country: 'США',
    duration: '180 мин.',
    poster: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=600&auto=format&fit=crop&q=80',
    description: 'Джордан Белфорт основывает успешную брокерскую контору и купается в роскоши, пока им не интересуется ФБР.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '16500',
    kinopoiskId: '689',
    imdbId: 'tt0241527',
    title: 'Гарри Поттер и философский камень',
    origTitle: "Harry Potter and the Sorcerer's Stone",
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2001',
    ratingKp: '8.3',
    ratingImdb: '7.6',
    genres: 'Фэнтези, Приключения, Семейный',
    country: 'Великобритания, США',
    duration: '152 мин.',
    poster: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd9?w=600&auto=format&fit=crop&q=80',
    description: 'Осиротевший мальчик узнает, что он волшебник, и отправляется учиться в школу чародейства и волшебства Хогвартс.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '17200',
    kinopoiskId: '328',
    imdbId: 'tt0120737',
    title: 'Властелин колец: Братство Кольца',
    origTitle: 'The Lord of the Rings: The Fellowship of the Ring',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2001',
    ratingKp: '8.6',
    ratingImdb: '8.9',
    genres: 'Фэнтези, Приключения, Драма',
    country: 'Новая Зеландия, США',
    duration: '178 мин.',
    poster: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
    description: 'Хоббит Фродо Бэггинс отправляется в опасное путешествие к Роковой горе, чтобы уничтожить Единое Кольцо.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '71900',
    kinopoiskId: '4386762',
    title: 'Сто лет тому вперед',
    origTitle: 'Сто лет тому вперед',
    categories: ['films', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '7.6',
    ratingImdb: '7.0',
    genres: 'Фантастика, Приключения',
    country: 'Россия',
    duration: '142 мин.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    description: 'Коля Герасимов знакомится с Алисой Селезневой из будущего, и вместе они спасают вселенную от космических пиратов.',
    isSeries: false,
    translators: [{ id: '1', name: 'Оригинал (Rus)', isDefault: true }],
  },
  {
    id: '71150',
    kinopoiskId: '5220626',
    title: 'Майор Гром: Игра',
    origTitle: 'Майор Гром: Игра',
    categories: ['films', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '7.8',
    ratingImdb: '7.2',
    genres: 'Боевик, Приключения, Детектив',
    country: 'Россия',
    duration: '168 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Майор полиции Игорь Гром сталкивается с новым суперзлодеем по прозвищу Призрак, угрожающим всему Петербургу.',
    isSeries: false,
    translators: [{ id: '1', name: 'Оригинал (Rus)', isDefault: true }],
  },

  // ==================== СЕРИАЛЫ ====================
  {
    id: '54201',
    kinopoiskId: '1354360',
    imdbId: 'tt3581920',
    title: 'Одни из нас',
    origTitle: 'The Last of Us',
    categories: ['series'],
    quality: '1080p Ultra',
    year: '2023',
    ratingKp: '8.0',
    ratingImdb: '8.8',
    genres: 'Фантастика, Драма, Приключения',
    country: 'США, Канада',
    duration: '55 мин.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    description: 'Джоэл должен вывести 14-летнюю девочку Элли из карантинной зоны через опустошенную грибком Америку.',
    isSeries: true,
    translators: [
      { id: '238', name: 'HDRezka Studio', isDefault: true },
      { id: '56', name: 'Дубляж (Red Head Sound)' },
      { id: '34', name: 'LostFilm' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия. Когда ты потерялся во тьме' },
      { seasonId: '1', episodeId: '2', name: '2 серия. Зараженные' },
      { seasonId: '1', episodeId: '3', name: '3 серия. Долгое-долгое время' },
      { seasonId: '1', episodeId: '4', name: '4 серия. Пожалуйста, держи меня за руку' },
      { seasonId: '1', episodeId: '5', name: '5 серия. Терпи и выживай' },
    ],
  },
  {
    id: '72301',
    kinopoiskId: '1391575',
    imdbId: 'tt12637874',
    title: 'Фоллаут',
    origTitle: 'Fallout',
    categories: ['series', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '8.1',
    ratingImdb: '8.4',
    genres: 'Фантастика, Боевик, Драма',
    country: 'США',
    duration: '60 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'В постапокалиптическом Лос-Анджелесе будущего жители Убежищ сталкиваются с жестоким миром Пустоши.',
    isSeries: true,
    translators: [
      { id: '238', name: 'HDRezka Studio', isDefault: true },
      { id: '56', name: 'Дубляж (Red Head Sound)' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия. Конец' },
      { seasonId: '1', episodeId: '2', name: '2 серия. Цель' },
      { seasonId: '1', episodeId: '3', name: '3 серия. Голова' },
      { seasonId: '1', episodeId: '4', name: '4 серия. Упыри' },
    ],
  },
  {
    id: '71001',
    kinopoiskId: '5309970',
    title: 'Слово пацана. Кровь на асфальте',
    origTitle: 'Слово пацана',
    categories: ['series'],
    quality: '1080p Ultra',
    year: '2023',
    ratingKp: '8.3',
    ratingImdb: '8.0',
    genres: 'Драма, Криминал',
    country: 'Россия',
    duration: '50 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Конец 1980-х годов. Подростки Казани делят улицы, формируя уличные группировки со своими суровыми законами.',
    isSeries: true,
    translators: [{ id: '1', name: 'Оригинал (Rus)', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия' },
      { seasonId: '1', episodeId: '2', name: '2 серия' },
      { seasonId: '1', episodeId: '3', name: '3 серия' },
      { seasonId: '1', episodeId: '4', name: '4 серия' },
    ],
  },
  {
    id: '74120',
    kinopoiskId: '4642784',
    imdbId: 'tt15435876',
    title: 'Пингвин',
    origTitle: 'The Penguin',
    categories: ['series', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '8.3',
    ratingImdb: '8.8',
    genres: 'Криминал, Драма',
    country: 'США',
    duration: '60 мин.',
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    description: 'Освальд Кобблпот стремится захватить власть над преступным миром Готэма после смерти Кармайна Фальконе.',
    isSeries: true,
    translators: [
      { id: '238', name: 'HDRezka Studio', isDefault: true },
      { id: '56', name: 'Дубляж (Red Head Sound)' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия. После полуночи' },
      { seasonId: '1', episodeId: '2', name: '2 серия. Внутренности' },
    ],
  },
  {
    id: '73900',
    kinopoiskId: '1172465',
    imdbId: 'tt2788316',
    title: 'Сёгун',
    origTitle: 'Shogun',
    categories: ['series', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '8.2',
    ratingImdb: '8.7',
    genres: 'Драма, Приключения, Военный, История',
    country: 'США',
    duration: '60 мин.',
    poster: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&auto=format&fit=crop&q=80',
    description: 'Япония начала XVII века. Английский штурман Джон Блэкторн терпит крушение и оказывается в центре феодальной борьбы за власть.',
    isSeries: true,
    translators: [
      { id: '238', name: 'HDRezka Studio', isDefault: true },
      { id: '34', name: 'LostFilm' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия. Аандзин' },
      { seasonId: '1', episodeId: '2', name: '2 серия. Слуги двух господ' },
    ],
  },
  {
    id: '21000',
    kinopoiskId: '464963',
    imdbId: 'tt0944947',
    title: 'Игра престолов',
    origTitle: 'Game of Thrones',
    categories: ['series'],
    quality: '1080p Ultra',
    year: '2011',
    ratingKp: '9.0',
    ratingImdb: '9.2',
    genres: 'Фэнтези, Драма, Боевик',
    country: 'США, Великобритания',
    duration: '55 мин.',
    poster: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
    description: 'К концу подходит время благоденствия, и лето, длившееся почти десятилетие, уступает место зиме. За Железный трон начинается смертельная битва.',
    isSeries: true,
    translators: [
      { id: '34', name: 'LostFilm', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия. Зима близко' },
      { seasonId: '1', episodeId: '2', name: '2 серия. Королевский тракт' },
    ],
  },
  {
    id: '50210',
    kinopoiskId: '1318972',
    imdbId: 'tt11198330',
    title: 'Дом Дракона',
    origTitle: 'House of the Dragon',
    categories: ['series', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '8.1',
    ratingImdb: '8.4',
    genres: 'Фэнтези, Боевик, Драма',
    country: 'США',
    duration: '60 мин.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    description: 'История дома Таргариенов за 200 лет до событий "Игры престолов". Междоусобная война за престол, известная как Танец Драконов.',
    isSeries: true,
    translators: [{ id: '238', name: 'HDRezka Studio', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }, { id: '2', name: '2 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия. Наследники Дракона' },
      { seasonId: '2', episodeId: '1', name: '1 серия. Сын за сына' },
    ],
  },
  {
    id: '18900',
    kinopoiskId: '404900',
    imdbId: 'tt0903747',
    title: 'Во все тяжкие',
    origTitle: 'Breaking Bad',
    categories: ['series'],
    quality: '1080p',
    year: '2008',
    ratingKp: '8.9',
    ratingImdb: '9.5',
    genres: 'Криминал, Драма, Триллер',
    country: 'США',
    duration: '47 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Школьный учитель химии Уолтер Уайт узнает о смертельном диагнозе и начинает производить метамфетамин ради будущего семьи.',
    isSeries: true,
    translators: [{ id: '34', name: 'LostFilm', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия. Пилот' },
      { seasonId: '1', episodeId: '2', name: '2 серия. Кот в мешке' },
    ],
  },
  {
    id: '31000',
    kinopoiskId: '915196',
    imdbId: 'tt4574334',
    title: 'Очень странные дела',
    origTitle: 'Stranger Things',
    categories: ['series'],
    quality: '1080p Ultra',
    year: '2016',
    ratingKp: '8.4',
    ratingImdb: '8.7',
    genres: 'Фантастика, Ужасы, Драма',
    country: 'США',
    duration: '50 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'В тихом городке Хоукинс исчезает мальчик, а его друзья сталкиваются с тайными экспериментами и потусторонним миром Изнанки.',
    isSeries: true,
    translators: [{ id: '238', name: 'HDRezka Studio', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Исчезновение Уилла Байерса' }],
  },

  // ==================== МУЛЬТФИЛЬМЫ ====================
  {
    id: '61205',
    kinopoiskId: '1309570',
    imdbId: 'tt9362722',
    title: 'Человек-паук: Паутина вселенных',
    origTitle: 'Spider-Man: Across the Spider-Verse',
    categories: ['cartoons', 'films'],
    quality: '1080p Ultra',
    year: '2023',
    ratingKp: '8.5',
    ratingImdb: '8.7',
    genres: 'Мультфильм, Фантастика, Боевик',
    country: 'США',
    duration: '140 мин.',
    poster: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=600&auto=format&fit=crop&q=80',
    description: 'Майлз Моралес отправляется в путешествие по Мультивселенной, где встречает команду Людей-пауков.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж (Red Head Sound)', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
  },
  {
    id: '31500',
    kinopoiskId: '924913',
    imdbId: 'tt4633694',
    title: 'Человек-паук: Через вселенные',
    origTitle: 'Spider-Man: Into the Spider-Verse',
    categories: ['cartoons', 'films'],
    quality: '1080p Ultra',
    year: '2018',
    ratingKp: '8.2',
    ratingImdb: '8.4',
    genres: 'Мультфильм, Фантастика, Боевик',
    country: 'США',
    duration: '117 мин.',
    poster: 'https://images.unsplash.com/photo-1604200213928-ba3cf4fc8436?w=600&auto=format&fit=crop&q=80',
    description: 'Подросток Майлз Моралес случайно обретает способности Человека-паука и объединяется с героями из параллельных миров.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '72500',
    kinopoiskId: '5129994',
    imdbId: 'tt22022452',
    title: 'Головоломка 2',
    origTitle: 'Inside Out 2',
    categories: ['cartoons', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '8.0',
    ratingImdb: '7.7',
    genres: 'Мультфильм, Семейный, Комедия',
    country: 'США',
    duration: '96 мин.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    description: 'Радость, Печаль, Гнев, Страх и Брезгливость встречают новых жильцов в голове подросшей Райли: Тревожность и ее спутников.',
    isSeries: false,
    translators: [
      { id: '56', name: 'Дубляж (Red Head Sound)', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
  },
  {
    id: '56000',
    kinopoiskId: '841813',
    imdbId: 'tt3915174',
    title: 'Кот в сапогах: Последнее желание',
    origTitle: 'Puss in Boots: The Last Wish',
    categories: ['cartoons'],
    quality: '1080p Ultra',
    year: '2022',
    ratingKp: '8.1',
    ratingImdb: '7.9',
    genres: 'Мультфильм, Комедия, Приключения',
    country: 'США',
    duration: '102 мин.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    description: 'Кот в сапогах потратил восемь из девяти своих жизней. Он отправляется в Темный лес на поиски Звезды желаний.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '29000',
    kinopoiskId: '679486',
    imdbId: 'tt2380307',
    title: 'Тайна Коко',
    origTitle: 'Coco',
    categories: ['cartoons'],
    quality: '1080p Ultra',
    year: '2017',
    ratingKp: '8.7',
    ratingImdb: '8.4',
    genres: 'Мультфильм, Фэнтези, Семейный',
    country: 'США',
    duration: '105 мин.',
    poster: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd9?w=600&auto=format&fit=crop&q=80',
    description: '12-летний Мигель мечтает стать музыкантом и попадает в красочную Страну Мертвых, где раскрывает тайну своей семьи.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '27100',
    kinopoiskId: '775276',
    imdbId: 'tt2948356',
    title: 'Зверополис',
    origTitle: 'Zootopia',
    categories: ['cartoons'],
    quality: '1080p Ultra',
    year: '2016',
    ratingKp: '8.3',
    ratingImdb: '8.0',
    genres: 'Мультфильм, Комедия, Детектив',
    country: 'США',
    duration: '108 мин.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    description: 'Жизнерадостная зайчиха Джуди Хоппс становится полицейским в городе животных и берется за раскрытие запутанного дела.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '72900',
    kinopoiskId: '4950669',
    imdbId: 'tt21692408',
    title: 'Кунг-фу Панда 4',
    origTitle: 'Kung Fu Panda 4',
    categories: ['cartoons', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '6.7',
    ratingImdb: '6.3',
    genres: 'Мультфильм, Боевик, Комедия',
    country: 'США, Китай',
    duration: '94 мин.',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    description: 'По предстоит стать Духовным лидером Долины Мира, но для этого ему нужно найти и обучить нового Воина Дракона.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж (Red Head Sound)', isDefault: true }],
  },

  // ==================== АНИМЕ ====================
  {
    id: '23100',
    kinopoiskId: '749377',
    imdbId: 'tt2560140',
    title: 'Атака титанов',
    origTitle: 'Shingeki no Kyojin',
    categories: ['animation', 'series'],
    quality: '1080p Ultra',
    year: '2013-2023',
    ratingKp: '8.7',
    ratingImdb: '9.1',
    genres: 'Аниме, Боевик, Фэнтези, Драма',
    country: 'Япония',
    duration: '24 мин.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    description: 'Остатки человечества укрываются за тремя исполинскими стенами от кровожадных титанов, пожирающих людей.',
    isSeries: true,
    translators: [
      { id: '238', name: 'HDRezka Studio', isDefault: true },
      { id: '11', name: 'AniLibria' },
      { id: '12', name: 'Studio Band' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [
      { seasonId: '1', episodeId: '1', name: '1 серия. К тебе, спустя две тысячи лет' },
      { seasonId: '1', episodeId: '2', name: '2 серия. В тот день' },
    ],
  },
  {
    id: '37200',
    kinopoiskId: '1205391',
    imdbId: 'tt9335498',
    title: 'Клинок, рассекающий демонов',
    origTitle: 'Kimetsu no Yaiba',
    categories: ['animation', 'series'],
    quality: '1080p Ultra',
    year: '2019-2024',
    ratingKp: '8.2',
    ratingImdb: '8.6',
    genres: 'Аниме, Боевик, Фэнтези',
    country: 'Япония',
    duration: '24 мин.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    description: 'Тандзиро Камадо становится истребителем демонов, чтобы отомстить за гибель семьи и исцелить обращенную сестру Недзуко.',
    isSeries: true,
    translators: [
      { id: '12', name: 'Studio Band', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Жестокость' }],
  },
  {
    id: '41000',
    kinopoiskId: '1319230',
    imdbId: 'tt12343534',
    title: 'Магическая битва',
    origTitle: 'Jujutsu Kaisen',
    categories: ['animation', 'series'],
    quality: '1080p Ultra',
    year: '2020-2024',
    ratingKp: '8.2',
    ratingImdb: '8.6',
    genres: 'Аниме, Фэнтези, Боевик',
    country: 'Япония',
    duration: '24 мин.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    description: 'Старшеклассник Юдзи Итадори проглатывает проклятый палец могущественного духа Сукуны и поступает в школу магов.',
    isSeries: true,
    translators: [
      { id: '12', name: 'Studio Band', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Двуликий призрак' }],
  },
  {
    id: '59200',
    kinopoiskId: '4365595',
    imdbId: 'tt13616990',
    title: 'Человек-бензопила',
    origTitle: 'Chainsaw Man',
    categories: ['animation', 'series'],
    quality: '1080p Ultra',
    year: '2022',
    ratingKp: '8.3',
    ratingImdb: '8.4',
    genres: 'Аниме, Боевик, Ужасы',
    country: 'Япония',
    duration: '24 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Дэндзи заключает сделку с демоническим псом Почитой и получает способность превращать конечности в смертоносные бензопилы.',
    isSeries: true,
    translators: [
      { id: '238', name: 'HDRezka Studio', isDefault: true },
      { id: '12', name: 'Studio Band' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Собака и бензопила' }],
  },
  {
    id: '72100',
    kinopoiskId: '4983050',
    imdbId: 'tt21209876',
    title: 'Поднятие уровня в одиночку',
    origTitle: 'Solo Leveling',
    categories: ['animation', 'series', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '8.4',
    ratingImdb: '8.4',
    genres: 'Аниме, Боевик, Фэнтези',
    country: 'Япония',
    duration: '24 мин.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    description: 'Самый слабый охотник Сон Джин-у чудом выживает в смертельном подземелье и получает уникальную систему бесконечного развития.',
    isSeries: true,
    translators: [
      { id: '12', name: 'Studio Band', isDefault: true },
      { id: '238', name: 'HDRezka Studio' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Я привык к этому' }],
  },
  {
    id: '16100',
    kinopoiskId: '370',
    imdbId: 'tt0245429',
    title: 'Унесённые призраками',
    origTitle: 'Sen to Chihiro no kamikakushi',
    categories: ['animation', 'films'],
    quality: '1080p Ultra',
    year: '2001',
    ratingKp: '8.5',
    ratingImdb: '8.6',
    genres: 'Аниме, Фэнтези, Приключения',
    country: 'Япония',
    duration: '125 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Девочка Тихиро попадает в заколдованный мир духов и богов, где её родители превращаются в свиней.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '19400',
    kinopoiskId: '49670',
    imdbId: 'tt0347149',
    title: 'Ходячий замок',
    origTitle: 'Howl no Ugoku Shiro',
    categories: ['animation', 'films'],
    quality: '1080p Ultra',
    year: '2004',
    ratingKp: '8.3',
    ratingImdb: '8.2',
    genres: 'Аниме, Фэнтези, Мелодрама',
    country: 'Япония',
    duration: '119 мин.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    description: 'Злая ведьма превращает 18-летнюю шляпницу Софи в дряхлую старуху. Девушка находит приют в ходячем замке волшебника Хаула.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '10300',
    kinopoiskId: '342',
    imdbId: 'tt0110912',
    title: 'Криминальное чтиво',
    origTitle: 'Pulp Fiction',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '1994',
    ratingKp: '8.6',
    ratingImdb: '8.9',
    genres: 'Криминал, Драма',
    country: 'США',
    duration: '154 мин.',
    poster: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&auto=format&fit=crop&q=80',
    description: 'Двое бандитов Винсент Вега и Джулс Винфилд проводят время в философских беседах в перерывах между разборками с должниками.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж (Гоблин)', isDefault: true }],
  },
  {
    id: '15100',
    kinopoiskId: '4374',
    imdbId: 'tt0325980',
    title: 'Пираты Карибского моря: Проклятие Черной жемчужины',
    origTitle: 'Pirates of the Caribbean: The Curse of the Black Pearl',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2003',
    ratingKp: '8.4',
    ratingImdb: '8.1',
    genres: 'Приключения, Фэнтези, Боевик',
    country: 'США',
    duration: '143 мин.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    description: 'Харизматичный авантюрист капитан Джек Воробей объединяется с кузнецом Уиллом Тернером, чтобы спасти дочь губернатора от пиратов-мертвецов.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '35000',
    kinopoiskId: '843650',
    imdbId: 'tt4154796',
    title: 'Мстители: Финал',
    origTitle: 'Avengers: Endgame',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2019',
    ratingKp: '7.9',
    ratingImdb: '8.4',
    genres: 'Фантастика, Боевик, Приключения',
    country: 'США',
    duration: '181 мин.',
    poster: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=600&auto=format&fit=crop&q=80',
    description: 'Оставшиеся в живых члены команды Мстителей разрабатывают дерзкий план путешествия во времени, чтобы вернуть уничтоженную Таносом половину вселенной.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '26000',
    kinopoiskId: '535341',
    imdbId: 'tt1675434',
    title: '1+1 (Неприкасаемые)',
    origTitle: 'Intouchables',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2011',
    ratingKp: '8.8',
    ratingImdb: '8.5',
    genres: 'Драма, Комедия, Биография',
    country: 'Франция',
    duration: '112 мин.',
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    description: 'Богатый аристократ Филипп, прикованный к инвалидному креслу, нанимает в качестве сиделки парня из предместья с криминальным прошлым.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '30200',
    kinopoiskId: '589290',
    imdbId: 'tt1856101',
    title: 'Бегущий по лезвию 2049',
    origTitle: 'Blade Runner 2049',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2017',
    ratingKp: '7.8',
    ratingImdb: '8.0',
    genres: 'Фантастика, Боевик, Триллер, Драма',
    country: 'США, Великобритания, Канада',
    duration: '164 мин.',
    poster: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    description: 'Офицер полиции Кей раскрывает давно погребенную тайну, способную погрузить остатки общества в хаос.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '11001',
    kinopoiskId: '41519',
    imdbId: 'tt0118767',
    title: 'Брат',
    origTitle: 'Брат',
    categories: ['films'],
    quality: '1080p',
    year: '1997',
    ratingKp: '8.3',
    ratingImdb: '7.9',
    genres: 'Боевик, Драма, Криминал',
    country: 'Россия',
    duration: '100 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Демобилизованный из армии Данила Багров приезжает в Санкт-Петербург к старшему брату, который оказывается наемным киллером.',
    isSeries: false,
    translators: [{ id: '1', name: 'Оригинал (Rus)', isDefault: true }],
  },
  {
    id: '11002',
    kinopoiskId: '41520',
    imdbId: 'tt0238883',
    title: 'Брат 2',
    origTitle: 'Брат 2',
    categories: ['films'],
    quality: '1080p',
    year: '2000',
    ratingKp: '8.2',
    ratingImdb: '7.7',
    genres: 'Боевик, Драма, Криминал',
    country: 'Россия, США',
    duration: '127 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Данила Багров отправляется в Америку, чтобы восстановить справедливость и выручить брата своего сослуживца.',
    isSeries: false,
    translators: [{ id: '1', name: 'Оригинал (Rus)', isDefault: true }],
  },
  {
    id: '71050',
    kinopoiskId: '5057762',
    title: 'Холоп 2',
    origTitle: 'Холоп 2',
    categories: ['films', 'new'],
    quality: '1080p Ultra',
    year: '2024',
    ratingKp: '7.1',
    ratingImdb: '6.5',
    genres: 'Комедия',
    country: 'Россия',
    duration: '119 мин.',
    poster: 'https://images.unsplash.com/photo-1533929736458-ca588d08c8be?w=600&auto=format&fit=crop&q=80',
    description: 'Бывший мажор Гриша решает проучить избалованную Катю и отправляет её на перевоспитание в эпоху войны 1812 года.',
    isSeries: false,
    translators: [{ id: '1', name: 'Оригинал (Rus)', isDefault: true }],
  },
  {
    id: '25100',
    kinopoiskId: '397667',
    imdbId: 'tt1130884',
    title: 'Остров проклятых',
    origTitle: 'Shutter Island',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2010',
    ratingKp: '8.5',
    ratingImdb: '8.2',
    genres: 'Триллер, Детектив, Драма',
    country: 'США',
    duration: '138 мин.',
    poster: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=600&auto=format&fit=crop&q=80',
    description: 'Два американских судебных пристава отправляются на остров в Бостонской бухте, чтобы расследовать исчезновение пациентки клиники для умалишенных.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '22400',
    kinopoiskId: '195334',
    imdbId: 'tt0482571',
    title: 'Престиж',
    origTitle: 'The Prestige',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '2006',
    ratingKp: '8.5',
    ratingImdb: '8.5',
    genres: 'Фантастика, Триллер, Драма, Детектив',
    country: 'Великобритания, США',
    duration: '130 мин.',
    poster: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&auto=format&fit=crop&q=80',
    description: 'Роберт и Альфред — фокусники-иллюзионисты в Лондоне рубежа веков. Их дружеское соперничество перерастает в беспощадную войну.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '10200',
    kinopoiskId: '389',
    imdbId: 'tt0110413',
    title: 'Леон',
    origTitle: 'Léon',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '1994',
    ratingKp: '8.7',
    ratingImdb: '8.5',
    genres: 'Боевик, Триллер, Драма, Криминал',
    country: 'Франция, США',
    duration: '110 мин.',
    poster: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&auto=format&fit=crop&q=80',
    description: 'Профессиональный киллер Леон берет под опеку 12-летнюю Матильду, чью семью расстреляли коррумпированные полицейские.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '10100',
    kinopoiskId: '448',
    imdbId: 'tt0109830',
    title: 'Форрест Гамп',
    origTitle: 'Forrest Gump',
    categories: ['films'],
    quality: '1080p Ultra',
    year: '1994',
    ratingKp: '8.9',
    ratingImdb: '8.8',
    genres: 'Драма, Комедия, Мелодрама, История',
    country: 'США',
    duration: '142 мин.',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    description: 'История добросердечного Форреста Гампа с уникальной судьбой, невольно ставшего свидетелем и участником важнейших событий эпохи.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },

  // Дополнительные сериалы
  {
    id: '27500',
    kinopoiskId: '685246',
    imdbId: 'tt2861424',
    title: 'Рик и Морти',
    origTitle: 'Rick and Morty',
    categories: ['series', 'cartoons'],
    quality: '1080p Ultra',
    year: '2013-2024',
    ratingKp: '9.0',
    ratingImdb: '9.1',
    genres: 'Мультсериал, Комедия, Фантастика',
    country: 'США',
    duration: '22 мин.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    description: 'Безумный ученый Рик Санчез путешествует по параллельным измерениям вместе со своим пугливым внуком Морти.',
    isSeries: true,
    translators: [
      { id: '238', name: 'HDRezka Studio', isDefault: true },
      { id: '56', name: 'Сыендук' },
    ],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Пилот' }],
  },
  {
    id: '22100',
    kinopoiskId: '502838',
    imdbId: 'tt1475582',
    title: 'Шерлок',
    origTitle: 'Sherlock',
    categories: ['series'],
    quality: '1080p Ultra',
    year: '2010-2017',
    ratingKp: '8.9',
    ratingImdb: '9.1',
    genres: 'Детектив, Триллер, Драма, Криминал',
    country: 'Великобритания, США',
    duration: '90 мин.',
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    description: 'Шерлок Холмс и доктор Джон Ватсон расследуют самые хитроумные преступления в современном Лондоне.',
    isSeries: true,
    translators: [{ id: '56', name: 'Дубляж (Первый канал)', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Этюд в розовых тонах' }],
  },
  {
    id: '35400',
    kinopoiskId: '1227967',
    imdbId: 'tt8624176',
    title: 'Чернобыль',
    origTitle: 'Chernobyl',
    categories: ['series'],
    quality: '1080p Ultra',
    year: '2019',
    ratingKp: '8.8',
    ratingImdb: '9.3',
    genres: 'Драма, История',
    country: 'США, Великобритания',
    duration: '60 мин.',
    poster: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=600&auto=format&fit=crop&q=80',
    description: '26 апреля 1986 года взрыв на Чернобыльской АЭС приводит к крупнейшей ядерной катастрофе в истории человечества.',
    isSeries: true,
    translators: [{ id: '238', name: 'HDRezka Studio', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. 1:23:45' }],
  },
  {
    id: '36000',
    kinopoiskId: '1044487',
    imdbId: 'tt1190634',
    title: 'Пацаны',
    origTitle: 'The Boys',
    categories: ['series', 'new'],
    quality: '1080p Ultra',
    year: '2019-2024',
    ratingKp: '8.2',
    ratingImdb: '8.7',
    genres: 'Фантастика, Боевик, Комедия, Криминал',
    country: 'США',
    duration: '60 мин.',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    description: 'Отряд мстителей без суперсил бросает вызов зарвавшимся и коррумпированным супергероям во главе с Хоумлендером.',
    isSeries: true,
    translators: [{ id: '238', name: 'HDRezka Studio', isDefault: true }, { id: '56', name: 'Кубик в кубе' }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Правила игры' }],
  },
  {
    id: '27800',
    kinopoiskId: '762838',
    imdbId: 'tt2442560',
    title: 'Острые козырьки',
    origTitle: 'Peaky Blinders',
    categories: ['series'],
    quality: '1080p Ultra',
    year: '2013-2022',
    ratingKp: '8.4',
    ratingImdb: '8.8',
    genres: 'Драма, Криминал',
    country: 'Великобритания',
    duration: '60 мин.',
    poster: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    description: 'Бирмингем, 1920-е годы. Гангстерский клан Шелби во главе с Томасом Шелби строит свою криминальную империю.',
    isSeries: true,
    translators: [{ id: '34', name: 'LostFilm', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия' }],
  },

  // Дополнительные мультфильмы
  {
    id: '19000',
    kinopoiskId: '279102',
    imdbId: 'tt0910970',
    title: 'ВАЛЛ-И',
    origTitle: 'WALL-E',
    categories: ['cartoons'],
    quality: '1080p Ultra',
    year: '2008',
    ratingKp: '8.3',
    ratingImdb: '8.4',
    genres: 'Мультфильм, Фантастика, Приключения, Семейный',
    country: 'США',
    duration: '98 мин.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    description: 'Маленький робот-мусорщик ВАЛЛ-И столетиями трудится на опустевшей Земле, пока не встречает робота ЕВУ.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '18500',
    kinopoiskId: '279930',
    imdbId: 'tt0382932',
    title: 'Рататуй',
    origTitle: 'Ratatouille',
    categories: ['cartoons'],
    quality: '1080p Ultra',
    year: '2007',
    ratingKp: '8.0',
    ratingImdb: '8.1',
    genres: 'Мультфильм, Комедия, Семейный',
    country: 'США',
    duration: '111 мин.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    description: 'Крысенок Реми обладает уникальным кулинарным даром и мечтает стать великим шеф-поваром в Париже.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '24000',
    kinopoiskId: '280175',
    imdbId: 'tt0892791',
    title: 'Как приручить дракона',
    origTitle: 'How to Train Your Dragon',
    categories: ['cartoons'],
    quality: '1080p Ultra',
    year: '2010',
    ratingKp: '8.2',
    ratingImdb: '8.1',
    genres: 'Мультфильм, Фэнтези, Приключения',
    country: 'США',
    duration: '98 мин.',
    poster: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80',
    description: 'Юный викинг Иккинг нарушает вековую традицию борьбы с драконами и заводит дружбу с раненой Ночной Фурией — Беззубиком.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },
  {
    id: '15500',
    kinopoiskId: '5030',
    imdbId: 'tt0298148',
    title: 'Шрек 2',
    origTitle: 'Shrek 2',
    categories: ['cartoons'],
    quality: '1080p Ultra',
    year: '2004',
    ratingKp: '8.0',
    ratingImdb: '7.3',
    genres: 'Мультфильм, Комедия, Фэнтези, Семейный',
    country: 'США',
    duration: '93 мин.',
    poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    description: 'Шрек и Фиона отправляются в Тридевятое королевство знакомиться с родителями принцессы.',
    isSeries: false,
    translators: [{ id: '56', name: 'Дубляж', isDefault: true }],
  },

  // Дополнительное аниме
  {
    id: '17800',
    kinopoiskId: '406148',
    imdbId: 'tt0877057',
    title: 'Тетрадь смерти',
    origTitle: 'Death Note',
    categories: ['animation', 'series'],
    quality: '1080p Ultra',
    year: '2006-2007',
    ratingKp: '8.6',
    ratingImdb: '8.9',
    genres: 'Аниме, Триллер, Детектив, Драма',
    country: 'Япония',
    duration: '23 мин.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80',
    description: 'Лучший ученик Японии Лайт Ягами находит тетрадь бога смерти и начинает вершить суд над преступниками под именем Кира.',
    isSeries: true,
    translators: [{ id: '56', name: 'Дубляж (2x2)', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Возрождение' }],
  },
  {
    id: '14200',
    kinopoiskId: '433555',
    imdbId: 'tt0409591',
    title: 'Наруто',
    origTitle: 'Naruto',
    categories: ['animation', 'series'],
    quality: '1080p',
    year: '2002-2007',
    ratingKp: '7.6',
    ratingImdb: '8.4',
    genres: 'Аниме, Боевик, Приключения, Фэнтези',
    country: 'Япония',
    duration: '23 мин.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    description: 'Юный ниндзя Наруто Узумаки мечтает превзойти всех и стать Хокаге — сильнейшим ниндзя и лидером своей деревни.',
    isSeries: true,
    translators: [{ id: '56', name: 'Дубляж (2x2)', isDefault: true }],
    seasons: [{ id: '1', name: '1 сезон' }],
    episodes: [{ seasonId: '1', episodeId: '1', name: '1 серия. Знакомьтесь, Наруто Узумаки' }],
  },
]

